export const REGISTRO_EXISTOSO = 'REGISTRO_EXISTOSO';
export const LOGIN_EXITOSO     = 'LOGIN_EXITOSO';
export const OBTENER_USUARIO   = 'OBTENER_USUARIO';
export const CERRAR_SESION     = 'CERRAR_SESION';
export const REGISTRO_USUARIO_ACTUALIZADO = 'REGISTRO_USUARIO_ACTUALIZADO';
export const CAMBIO            = 'CAMBIO';

//alertas en login y edicion
export const LOGIN_ERROR          = 'LOGIN_ERROR';
export const LIMPIAR_ERROR_ALERTA = 'LIMPIAR_ERROR_ALERTA';
export const ALERTAS_ACTUALIZACION_USER = 'ERRORES_ACTUALIZACION_USER';
export const LIMPIAR_ALERTAS_USER = 'LIMPIAR_ALERTAS_USER';

//archivos del usuario 
export const SUBIDA_ARCHIVO   = 'SUBIDA_ARCHIVO';
export const OBTENER_ARCHIVOS = 'OBTENER_ARCHIVOS';
export const ELIMINAR_ARCHIVO = 'ELIMINAR_ARCHIVO';
export const REGRESAR_CAMBIO_ARCHIVO = 'REGRESAR_CAMBIO_ARCHIVO';
